// <auto-generated />
using System;
using Infrestructure.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrestructure.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20231129083850_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.CitiesLatAndLang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Lang")
                        .HasColumnType("real");

                    b.Property<float>("Lat")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CitiesLatAndLangs");
                });

            modelBuilder.Entity("Core.Entities.Ejucation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Academy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Beginning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgrammeDuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("badgeLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("idSite")
                        .HasColumnType("int");

                    b.Property<bool?>("isCompleteOnlinePossible")
                        .HasColumnType("bit");

                    b.Property<bool?>("isElearning")
                        .HasColumnType("bit");

                    b.Property<float?>("lang")
                        .HasColumnType("real");

                    b.Property<float?>("lat")
                        .HasColumnType("real");

                    b.Property<string>("link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("requestLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("structuredResearch")
                        .HasColumnType("bit");

                    b.Property<string>("subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typeCourseDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ejucations");
                });

            modelBuilder.Entity("Core.Entities.Job", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<float?>("Lang")
                        .HasColumnType("real");

                    b.Property<string>("applicationsCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contractType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("experienceLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jobUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jobid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("lat")
                        .HasColumnType("real");

                    b.Property<string>("location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("postedTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("posterFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("posterProfileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("publishedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("salary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("workType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
